#!/usr/bin/python

import os
import stat
import json
import sys
import urllib
import pysvn
import subprocess
import shutil
import pwd
import grp
import hashlib
import ConfigParser
from optparse import OptionParser, OptionGroup

#### TODO TODO TODO TODO
# TODO - different output formats (csv? xml? json?)
# TODO verbose() command and output() command?
# TODO log runScripts? print in verbose mode

## "check" property
### before increment it checks all files with "check" property
#### check value can be:
#### - fail - Fail the entire package upgrade if the local file has changed - DOES NOT OVERWRITE
#### - ignore - (default) - Do nothing - don't care - OVERWITES LOCAL CHANGES
#### - warn - Warn the file has changed - OVERWRITES LOCAL CHANGES
#### - skip - don't change /that/ file, and that file alone, on the next increment - DOES NOT OVERWRITE
def checkForLocalChanges(scsroot,pkg):
	ignoreList = []
	svnclient = pysvn.Client()
	propList = svnclient.proplist(os.path.join(scsroot,'packages',pkg,'data'),recurse=True)

	for propSet in propList:
		source     = propSet[0]
		properties = propSet[1]

		if 'dest' in properties:
			dest = properties['dest']

			print 'SCS: Checking for local changes on ' + dest

			## Get SHA sums
			try:
				sourceh = shasum(source)
				desth   = shasum(dest)
			except Exception as e:
				print 'SCS: Cannot check for local changes on ' + dest + ': ' + str(e)
			else:
				## Compare sums
				if not sourceh == desth:

					print 'SCS: The file ' + dest + ' has been modified outside of SCS control'

					## TODO FUTURE make the default come from a revprop?
					checkAction = 'ignore'

					if 'check' in properties:
						checkAction = properties['check']

					print 'SCS: The file has been configured to "' + checkAction + '" in this scenario'

					if checkAction == 'fail':
						print "SCS: ERROR! Local changes found to file " + dest
						print "SCS: ERROR! Transaction failed. Could not init pkg"
						return 0
					elif checkAction == 'warn':
						print "SCS: WARNING! Local changes found to file " + dest
					elif checkAction == 'skip':
						## add the file to the "ignore" list
						ignoreList.append(source)

	return ignoreList

################################################################################
################################################################################

def packageInstalled(scsroot,pkg):
	if os.path.exists(os.path.join(scsroot,'packages',pkg)):
		return True
	else:
		return False

################################################################################
################################################################################

def listFiles(scsroot,pkg):
	svnclient = pysvn.Client()
	propList = svnclient.proplist(os.path.join(scsroot,'packages',pkg,'data'),recurse=True)

	for propSet in propList:
		source     = propSet[0]
		properties = propSet[1]

		if 'dest' in properties:
			dest = properties['dest']
			print '{0:38}  {1:38}'.format(dest, source)

################################################################################
################################################################################

def shasum(filePath,blocksize=2**20):
	sha = hashlib.sha256()
	f = open(filePath,'rb')
	while True:
		data = f.read(blocksize)
		if not data:
			break;
		sha.update(data)
	return sha.hexdigest()

################################################################################
################################################################################

def runScript(scsroot,pkgName,scriptName):
	print 'SCS: Executing ' + scriptName + ' on package ' + pkgName
	scriptPath = os.path.join(scsroot,'packages',pkgName,'scripts',scriptName)

	## CHMOD First
	os.chmod(scriptPath,stat.S_IRWXU)

	print scriptPath

	if os.path.getsize(scriptPath) == 0:
		print "SCS: Script is empty; not executing"
		return (0, '', '')

	## Now run the script
	try:
		script = subprocess.Popen([scriptPath],stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
		(stdoutdata, stderrdata) = script.communicate()
		return (script.returncode, stdoutdata, stderrdata)
	except OSError as e:
		## UNIX codes will only ever be 0-255
		## Thus use -1 to signify an OS error
		print 'SCS: Execution of script ' + scriptName + ' failed: ' + str(e)
		return (-1,str(e),str(e))

################################################################################
################################################################################

def fetchMetadata(metadataUrl):
	#print 'Fetching metadata...'
	try:
		f = urllib.urlopen(metadataUrl)
		jsonData = f.read()
		f.close()
	except IOError as e:
		print 'Unable to read from ' + e.filename + ': ' + e.strerror
		sys.exit(1)

	try:
		metadict = json.loads(jsonData)
	except (TypeError,ValueError) as e:
		print 'Unable to understand server metadata: ' + str(e)
		sys.exit(2)

	return metadict

################################################################################
################################################################################

def processPackage(pkg):
	if type(pkg).__name__=='dict':
		if pkg.has_key('name') and pkg.has_key('revision') and pkg.has_key('desc'):
			print str(pkg['name']) + '-' + str(pkg['revision']) + "\t\t" + str(pkg['desc'])
		elif pkg.has_key('name') and pkg.has_key('revision'):
			print str(pkg['name']) + '-' + str(pkg['revision'])
		else:
			print 'fail2'
	else:
		print 'uh oh - that was not a dict!'

################################################################################
################################################################################

def processPackageFromJson(jsonData):
	try:
		pkg = json.loads(jsonData)
	except (TypeError,ValueError) as e:
		print 'Unable to understand data: ' + str(e)
	else:
		processPackage(pkg)

################################################################################
################################################################################

def processPackagesFromJson(jsonData):
	try:
		pkgs = json.loads(jsonData)
	except (TypeError,ValueError) as e:
		print 'Unable to understand data: ' + str(e)

	if type(pkgs).__name__=='list':
		for pkg in pkgs:
			processPackage(pkg)
	else:
		print 'uh oh - that was not a list!'

################################################################################
################################################################################

def main():
	#### HELP TEXT FOR ACTIONS
	usage = '''Usage: %prog [options] ACTION [...]

    Update functions:

        check                      List available updates from channels
        update                     Apply all updates from all channels
        update        CHANNEL      Apply updates from a channel
        upgrade       PACKAGE      Upgrade a specific package (Not recommended)

    Basic package functions:

        installed                  List installed packages
        packages                   List all available packages
        init          PACKAGE      Install a package
        uninit        PACKAGE      Remove a package

    Package maintenance functions: 

        verify        PACKAGE      Verify system conforms to package spec
        verify-all                 Verify system conforms to all package specs
		files         PACKAGE      List files which are part of PACKAGE
        files-all                  List files from all packages
        owner         FILEPATH     Determine if FILEPATH is owned by a package

    Channel-related actions:
        subscribed                 List channels this system is subscribed to
        channels                   List all available channels 
        subscribe     CHANNEL      Subscribe to a channel
        unsubscribe   CHANNEL      Unsubscribe from a channel'''

	## Set a 'good' working directory
	os.chdir('/tmp')

	#### COMMAND LINE PARSER
	parser = OptionParser(usage=usage,version='%prog version 2')
	parser.add_option('-c','--config-file',dest='config',default="/etc/scs.conf",help='Set the configuration file to use')
	parser.add_option('-f','--force',dest='ignore',default=False,action="store_true",help='Ignore local changes and proceed anyway')
	group = OptionGroup(parser,"Options for 'init'")
	group.add_option('-r','--revision',type="int",default=-1,dest='revision',help='Specify a specific revision of the package to tag')
	parser.add_option_group(group)
	(options, args) = parser.parse_args()

	#### LOAD CONFIG
	config = ConfigParser.RawConfigParser()
	config.read(options.config)

	scsroot = '/opt/scs/'
	svnroot = ''
	metaurl = ''

	if config.has_option('client','scs root'):
		configValue = config.get('client','scs root')
		if os.path.isdir(configValue):
			scsroot = configValue
		else:
			print >> sys.stderr, 'The scs root specified in ' + options.config + ' is not a directory'
			sys.exit(1)

	if config.has_option('client','svn root'):
		svnroot = config.get('client','svn root')
	else:
		print 'No svn root defined in ' + options.config
		sys.exit(1)

	if config.has_option('client','metadata url'):
		metaurl = config.get('client','metadata url')
	else:
		print 'No metadata url defined in ' + options.config
		sys.exit(1)

	#### SWTICH ACTIONS
	if len(args) < 1:
		parser.print_help()
	else:
		action = args[0]
		svnclient = pysvn.Client()

################################################################################

		if action == 'installed':
			pkgs = os.listdir(os.path.join(scsroot,'packages'))

			for pkg in pkgs:
				try:
					f = open(os.path.join(scsroot,'packages',pkg,'conf','metadata.json'), 'r')
					jsonData = f.read()
					f.close()
				except IOError as e:
					print 'Unable to read from ' + e.filename + ': ' + e.strerror
					sys.exit(1)

				processPackageFromJson(jsonData)

			## TODO reformat output?

################################################################################

		elif action == 'packages':
			metadict = fetchMetadata(metaurl)

			for pkgName in metadict['packages']:
				pkg = metadict['packages'][pkgName]
				if pkg.has_key('name'):
					print str(pkg['name'])

			## TODO reformat output?

################################################################################

		elif action == 'verify':
			## Store package name in a friendly variable
			pkg = args[1]

			if packageInstalled(scsroot,pkg):
				dataPath = os.path.join(scsroot,'packages',pkg,'data')
				checkForLocalChanges(scsroot,pkg)
			else:
				print 'SCS: No such package'
				sys.exit(1)

################################################################################

		elif action == 'verify-all':
			pkgs = os.listdir(os.path.join(scsroot,'packages'))
			for pkg in pkgs:
				print 'SCS: Checking for local changes to pkg "' + pkg + '"'
				checkForLocalChanges(scsroot,pkg)

################################################################################

		elif action == 'files':
			pkg = args[1]

			if packageInstalled(scsroot,pkg):
				dataPath = os.path.join(scsroot,'packages',pkg,'data')
				listFiles(scsroot,pkg)
			else:
				print 'SCS: No such package'
				sys.exit(1)

################################################################################

		elif action == 'files-all':
			pkgs = os.listdir(os.path.join(scsroot,'packages'))
			for pkg in pkgs:
				print 'SCS: List files in pkg "' + pkg + '"'
				listFiles(scsroot,pkg)

################################################################################
		elif action == 'init' and len(args) == 2:

			## Store package name in a friendly variable
			pkg = args[1]

			## Get metadata from server
			metadict = fetchMetadata(metaurl)

			## See if the package requested actually exists
			found = False
			for pkgName in metadict['packages']:
				if pkgName == pkg:
					found = True

			## Catch errors
			if not found:
				print 'No such package'
				sys.exit(1)

			## Work out paths
			remotePath   = svnroot + '/p_' + pkg + '/' 
			localPath    = os.path.join(scsroot,'packages',pkg)
			localScripts = os.path.join(localPath,'scripts')
			localData    = os.path.join(localPath,'data')
			
			## Get latest remote revision
			infoList = svnclient.info2(remotePath,recurse=False)
			for infoTuple in infoList:
				infoDict = infoTuple[1]
				latestRevision = infoDict['rev'].number

			## Get local revision installed
			infoList = svnclient.info2(localData,recurse=False)
			for infoTuple in infoList:
				infoDict = infoTuple[1]
				localRevision = infoDict['rev'].number

			if localRevision == latestRevision:
				print 'SCS: Already up to date'
				revisionToUse = pysvn.Revision(pysvn.opt_revision_kind.head)
				#return 1
			else:
				revisionToUse = pysvn.Revision(pysvn.opt_revision_kind.number, int(localRevision) + 1)

			## TODO FUTURE get revprop to see if we should skip this revision or not

			## What type, init or upgrade?
			upgrade = False

			## A list of files to ignore during property-apply phase
			ignoreList = []

			## If this is an upgrade
			if os.path.exists(localPath):
				upgrade = True
				print 'SCS: Upgrading ' + pkg

				## Should we ignore local changes?
				ignore = options.ignore

				## If we shouldn't then check for local changes
				if not ignore:
					print 'SCS: Checking for local changes'			
					ignoreList = checkForLocalChanges(scsroot,pkg)

				## Pre-increment ("pre-upgrade") script
				(scode,sout,serr) = runScript(scsroot,pkg,'preinc')
				if scode > 0:
					print 'SCS: preinc script returned non-zero, cancelling pkg init'
					return 1
				
			else:
				print 'SCS: Installing ' + pkg

				## set up directory layout
				try:
					os.mkdir(localPath)
					os.mkdir(os.path.join(localPath,'conf'))
					os.mkdir(os.path.join(localPath,'scripts'))
					os.mkdir(os.path.join(localPath,'data'))
				except (OSError, IOError) as error:
					print 'Failed to init package. Error was: ' + error.strerror + ' on ' + error.filename
					sys.exit(0)
	
			print 'SCS: Deploying scripts'
			print remotePath + 'scripts'
			print localScripts
			print revisionToUse.number
			svnclient.export(remotePath + 'scripts',localScripts,revision=revisionToUse,force=True,recurse=True)

			## If initial init, use "checkout", if not, use "update"
			if upgrade:
				print 'SCS: Updating package data'
				svnclient.update(localData,revision=revisionToUse)
			else:
				print 'SCS: Deploying package data'
				svnclient.checkout(remotePath + 'data',localData,revision=revisionToUse)

			## Run scripts
			if upgrade:
				(scode,sout,serr) = runScript(scsroot,pkg,'preup')
				if scode > 0:
					print 'SCS: preup script returned non-zero, cancelling pkg init'
					return 1
			else:
				(scode,sout,serr) = runScript(scsroot,pkg,'preinit')
				if scode > 0:
					print 'SCS: preinc script returned non-zero, cancelling pkg init'
					return 1

			(scode,sout,serr) = runScript(scsroot,pkg,'preinst')
			if scode > 0:
				print 'SCS: preinc script returned non-zero, cancelling pkg init'
				return 1

			## Get properties
			propList = svnclient.proplist(localData,recurse=True)

			for propSet in propList:
				source     = propSet[0]
				properties = propSet[1]

				## Skip files marked as "skip" during check for local changes phase
				if source in ignoreList:
					print 'Skipping file ' + source + ' from inst stage due to local changes'
					continue;

				## Core properties
				## dest - file location to copy/link/hardlink to, e.g. /etc/openldap.conf - implies preserve

				## By default, apply properties to where the file is downloaded to via SVN
				dest = source

				#print '----------'
				#print 'source is ' + source

				if 'dest' in properties:
					dest = properties['dest']
					action = 'copy'


					#print 'dest is ' + dest

					if 'action' in properties:
						action = properties['action']

					#print 'mode is ' + action

					chattr = subprocess.Popen(['chattr', '-i', dest],stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
					(stdoutdata, stderrdata) = chattr.communicate()
					retcode = chattr.returncode
					## TODO errors ^

					if action == 'copy':
						## copy the file
						try:
							shutil.copyfile(source,dest)
						except IOError as e:
							print "Unable to copy from " + source + " to " + dest + ": " + str(e)

					elif action == 'link':
						try:
							os.symlink(source,dest)
						except (IOError, OSError) as e:
							print "Unable to link " + source + " to " + dest + ": " + str(e)

					elif action == 'linkr':
						try:
							if os.path.isdir(dest):
								shutil.rmtree(dest)
							elif os.path.isfile(dest):
								os.unlink(dest)
							os.symlink(source,dest)
						except (IOError, OSError) as e:
							print "Unable to linkr " + source + " to " + dest + ": " + str(e)

					elif action == 'linko':
						try:
							if os.path.isfile(dest):
								os.unlink(dest)
							os.symlink(source,dest)
						except (IOError, OSError) as e:
							print "Unable to linko " + source + " to " + dest + ": " + str(e)

				## chmod - set the permissions to octal mode
				if 'chmod' in properties:
					print "\t" + properties['chmod']
					os.chmod(dest,int(properties['chmod'],8))
					## TODO exceptions

				## owner - set the owner to
				if 'owner' in properties:
					pwd = pwd.getpwnam(properties['owner'])
					uid = pwd[2]
					os.chown(dest,uid)
					## TODO exceptions

				## group - set the group to
				if 'group' in properties:
					grp = grp.getgrnam(properties['group'])
					gid = grp[2]
					os.chown(dest,-1,gid)
					## TODO exceptions

				if 'uid' in properties:
					os.chown(dest,properties['uid'],-1)
					## TODO exceptions

				## group - set the group to
				if 'gid' in properties:
					os.chown(dest,-1,properties['gid'])
					## TODO exceptions

				## immutable - set the file to immutable after
				if 'immutable' in properties:
					## NOTE although python has os.chflags, due to a python configure bug they
					## are NEVER compiled in - stupid python.

					chattr = subprocess.Popen(['chattr', '+i', dest],stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
					(stdoutdata, stderrdata) = chattr.communicate()
					retcode = chattr.returncode
					## TODO errors ^

					if retcode > 0:
						print stdoutdata, stderrdata

			runScript(scsroot,pkg,'postinst')
			## TODO RESULTACT if the above returns a non-zero then warnings are printed!

			if upgrade:
				## Pre-upgrade script
				runScript(scsroot,pkg,'postup')
				## TODO RESULTACT if the above returns a non-zero then warnings are printed!
			else:
				## Post init script
				runScript(scsroot,pkg,'postinit')
				## TODO RESULTACT if the above returns a non-zero then warnings are printed!

			## TODO output from commands?/copies?

			## TODO Update meta??
				## write name and revision to metadata.json???

################################################################################

		elif action == 'uninit':
			print 'todo'

################################################################################

		elif action == 'channels':
			metadict = fetchMetadata(metaurl)

			for cName in metadict['channels']:
				channel = metadict['channels'][cName]
				if channel.has_key('name'):
					print str(channel['name'])

################################################################################

		elif action == 'subscribed':
			print 'todo'

################################################################################

		elif action == 'subscribe':
			print 'todo'

################################################################################

		elif action == 'unsubscribe':
			print 'todo'

################################################################################

if __name__ == "__main__":
    main()

