#!/usr/bin/python
# Subversion Configuration System Manager

#### IMPORTS
import scslib
from optparse import OptionParser, OptionGroup
import subprocess
import os
import sys
import shutil
import re
import pysvn
import ConfigParser
import json
import fcntl
#import time

## TODO
# chan-info

def main():
	#### HELP TEXT FOR ACTIONS
	usage = '''Usage: %prog [options] ACTION [...]

    Package-related actions:
        pkg-create    NAME         Create a package
        pkg-delete    NAME         Deletes a package
		pkg-list                   Lists all packages

    Channel-related actions:
        chan-create   NAME         Create a channel
        chan-delete   NAME         Deletes a channel
        chan-list                  Lists all channels
T       chan-info     NAME         Show channel contents
	  
    Other actions:
        tag           CHANNEL PACKAGE
                      Adds the specified package name to the channel
        untag         CHANNEL PACKAGE
                      Removes the specified package name from the channel  
        priority      CHANNEL PACKAGE PRIORITY
                      Sets the installation order PRIORITY on PACKAGE in CHANNEL'''

## TODO chan-info

	#### COMMAND LINE PARSER
	parser = OptionParser(usage=usage,version='%prog version 2')
	parser.add_option('-c','--config-file',dest='config',default="/etc/scs.conf",help='Set the configuration file to use')
	group = OptionGroup(parser,"Options for 'pkg-create'")
	group.add_option('-s','--step-free',action='store_true',dest='stepfree',default=False,help='Create a non-transactional package')
	parser.add_option_group(group)
	group = OptionGroup(parser,"Options for 'tag'")
	group.add_option('-r','--revision',type="int",default=-1,dest='revision',help='Specify a specific revision of the package to tag')
	group.add_option('-o','--install-order',type="int",default=-1,dest='instorder',help='Set a installation priority to let scs known what order to install packages')
	parser.add_option_group(group)
	(options, args) = parser.parse_args()

	## Load configuration variables
	(svnroot,scsmroot,metadataPath) = scslib.sLoadConfig(options.config);

	## Get metadata
	metadict = scslib.sLockAndLoad(metadataPath)

	## Load subversion library
	svnclient = pysvn.Client()

	## Build other paths
	pkgcodir  = os.path.join(scsmroot,'packages')
	chancodir = os.path.join(scsmroot,'channels')

	## Deal with no args
	if len(args) <= 0:
		parser.print_help()
		sys.exit(0)
			
	## Shortcut to action
	action = args[0]

	#### CHANNEL CREATE ####################################################
	if action == 'chan-create' and len(args) == 2:
		name = args[1]

		if metadict['channels'].has_key(name):
			print "Sorry, that channel already exists!"
			sys.exit(1)

		## Workout the SVN root should be
		svnpath = os.path.join(svnroot,'c_' + name)

		## Create it there
		svn_create(svnpath,name,'channel')

		## Checkout
		codir = os.path.join(chancodir,'c_' + name)
		svnclient.checkout('file://' + svnpath, codir)

		## Create packages dir
		try:
			os.mkdir(os.path.join(codir,'packages'))
		except (OSError, IOError) as error:
			print 'Failed to create base components of channel. Error was: ' + error.strerror + ' on ' + error.filename
		else:
			svnclient.add(os.path.join(codir,'packages'))
			revision = svnclient.checkin(codir,"Channel creation",recurse=True)
			metadict['channels'][name] = {'name': name}

	#### CHANNEL DELETE ####################################################
	elif action == 'chan-delete' and len(args) == 2:
		name = args[1]
		svn_delete(os.path.join(svnroot,'c_' + name),'channel')
		shutil.rmtree(os.path.join(chancodir,'c_' + name))

	#### CHANNEL LIST ######################################################
	elif action == 'chan-list':
		for channame in metadict['channels']:
			chandict = metadict['channels'][channame]
			print chandict['name']

	#### CHANNEL TAG #######################################################
	elif action == 'tag' and len(args) == 3:
		## Setup variables
		channelName     = args[1]
		packageName     = args[2]
		pkgSvnPath      = os.path.join(svnroot,'p_' + packageName)
		pkgCheckout     = os.path.join(pkgcodir,'p_' + packageName)
		channelCheckout = os.path.join(chancodir,'c_' + channelName)
		pkgConfigFile   = os.path.join(channelCheckout,'packages',packageName)
		pkgUpgradeFile  = os.path.join(channelCheckout,'upgrade')

		if not metadict['channels'].has_key(channelName):
			print "Sorry, that channel does not exist!"
			sys.exit(1)

		if not metadict['packages'].has_key(packageName):
			print "Sorry, that channel does not exist!"
			sys.exit(1)

		## Make sure channel is up-to-date
		svnclient.update(os.path.join(chancodir,'c_' + channelName))

		## Checkout the package into a temporary directory
		infoList = svnclient.info2('file://' + pkgSvnPath + '/',recurse=False,revision=pysvn.Revision(pysvn.opt_revision_kind.head))
		currentPackageRevision = infoList[0][1].rev.number

		## Was there a specific revision to use?
		if options.revision >= 0:
			if options.revision >= currentPackageRevision:
				print 'Invalid package revision'
				sys.exit(0)
			else:
				taggedRevision = options.revision
		else:
			taggedRevision = currentPackageRevision

		## make sure the new revision is higher than the current revision, if any
		if os.path.isfile(pkgConfigFile):
			currentRev = svnclient.propget('revision',pkgConfigFile)
			currentRev = currentRev[pkgConfigFile]

			if int(currentRev) == int(taggedRevision):
				print 'The package is already tagged to that revision'
				sys.exit(0)
			elif int(currentRev) > int(taggedRevision):
				print 'The package is already tagged to a more recent revision'
				sys.exit(0)

		## Touch the package name in packages/ in the channel
		try:
			### Remove all previous properties on the upgrade file if it exists
			if os.path.isfile(pkgUpgradeFile):
				svnclient.propdel('name',pkgUpgradeFile)
				svnclient.propdel('revision',pkgUpgradeFile)
				svnclient.propdel('action',pkgUpgradeFile)
			else:
				#### Add the upgrade file cos it hasn't been used yet
				open(pkgUpgradeFile,'w')
				svnclient.add(pkgUpgradeFile)

			## Touch channel/packages/packageName
			if not os.path.isfile(pkgConfigFile):
				open(pkgConfigFile,'w')
				svnclient.add(pkgConfigFile)

			## Set name and revision on "upgrade" file
			svnclient.propset('name',packageName,pkgUpgradeFile)
			svnclient.propset('revision',str(taggedRevision),pkgUpgradeFile)
			svnclient.propset('action','install',pkgUpgradeFile)

			## Set revision on the config file (for new installs)
			svnclient.propset('name',packageName,pkgConfigFile)
			svnclient.propset('revision',str(taggedRevision),pkgConfigFile)

			## Set an install order if requested
			if options.instorder >= 0:
				svnclient.propset('order',str(options.instorder),pkgConfigFile)

			## Checkin
			revision = svnclient.checkin(channelCheckout,"Added version " + str(taggedRevision) + ' of ' + packageName + ' into channel ' + channelName,recurse=True)
		
		except (OSError, IOError) as error:
			print 'Failed to tag package into channel. Error was: ' + error.strerror + ' on ' + error.filename

		except pysvn.ClientError as error:
			print 'Subversion operation failed: ' + str(error)

	#### CHANNEL UNTAG #####################################################
	elif action == 'untag' and len(args) == 3:

		## Setup variables
		channelName     = args[1]
		packageName     = args[2]
		channelCheckout = os.path.join(chancodir,'c_' + channelName)
		pkgConfigFile   = os.path.join(channelCheckout,'packages',packageName)
		pkgUpgradeFile  = os.path.join(channelCheckout,'upgrade')

		if not metadict['channels'].has_key(channelName):
			print "Sorry, that channel does not exist!"
			sys.exit(1)

		if not metadict['packages'].has_key(packageName):
			print "Sorry, that package does not exist!"
			sys.exit(1)

		## Make sure channel is up-to-date
		svnclient.update(os.path.join(chancodir,'c_' + channelName))

		## is this pkg already tagged? Check the packages/ dir
		if not os.path.isfile(pkgConfigFile):
			print 'The package is not tagged to the channel'
			sys.exit(0)

		try:
			### Remove all previous properties on the upgrade file if it exists
			if os.path.isfile(pkgUpgradeFile):
				svnclient.propdel('name',pkgUpgradeFile)
				svnclient.propdel('revision',pkgUpgradeFile)
				svnclient.propdel('action',pkgUpgradeFile)
			else:
				#### Add the upgrade file cos it hasn't been used yet
				open(pkgUpgradeFile,'w')
				svnclient.add(pkgUpgradeFile)

			## Delete channel/packages/packageName
			os.unlink(pkgConfigFile)
			svnclient.remove(pkgConfigFile)

			## Set the upgrade properties to remove the package
			svnclient.propset('name',packageName,pkgUpgradeFile)
			svnclient.propset('action','remove',pkgUpgradeFile)

			## Checkin
			revision = svnclient.checkin(channelCheckout,"Removed " + packageName + ' from channel ' + channelName,recurse=True)
		
		except (OSError, IOError) as error:
			print 'Failed to untag package from channel. Error was: ' + error.strerror + ' on ' + error.filename

		except pysvn.ClientError as error:
			print 'Subversion operation failed: ' + str(error)

	#### PRIORITY #####################################################
	elif action == 'priority' and len(args) == 4:

		## Setup variables
		channelName     = args[1]
		packageName     = args[2]
		installOrder    = args[3]
		channelCheckout = os.path.join(chancodir,'c_' + channelName)
		pkgConfigFile   = os.path.join(channelCheckout,'packages',packageName)

		if not metadict['channels'].has_key(channelName):
			print "Sorry, that channel does not exist!"
			sys.exit(1)

		if not metadict['packages'].has_key(packageName):
			print "Sorry, that channel does not exist!"
			sys.exit(1)

		## Make sure channel is up-to-date
		svnclient.update(os.path.join(chancodir,'c_' + channelName))

		try:
			## Set the svn property
			svnclient.propset('order',str(installOrder),pkgConfigFile)

			## Checkin
			revision = svnclient.checkin(channelCheckout,"Removed " + packageName + ' from channel ' + channelName,recurse=True)

		except pysvn.ClientError as error:
			print 'Subversion operation failed: ' + str(error)

	else:
		parser.print_help()

	## Save metadata
	scslib.sSaveAndUnlock(metadict)

if __name__ == "__main__":
	if sys.version < '2.6':
		fatal('Wrong Python Version !!!')
	else:
	    main()
