#!/usr/bin/python
# Subversion Configuration System Manager

#### IMPORTS
import scslib
from scslib import inform, meta, svnclient
from optparse import OptionParser, OptionGroup
import os
import sys
import shutil
import pysvn
import atexit

def main():
	## Require root
	scslib.requireRoot()

	usage = '''Usage: %prog [options] ACTION [...]
	
    list                                      Lists all packages
    create    NAME                            Create a package
    delete    NAME                            Deletes a package
    clone     EXISTING-NAME CLONED-NAME       Clone an existing package 
    set       NAME PROPERTY VALUE             Set a package property to VALUE'''

	#### COMMAND LINE PARSER
	parser = OptionParser(usage=usage,version="scs version " + scslib.versionStr())
	parser.add_option('-c','--config-file',dest='config',default="/etc/scs.conf",help='Set the configuration file to use')
	group = OptionGroup(parser,"Options for 'create'")
	group.add_option('-s','--step-free',action='store_true',dest='stepfree',default=False,help='Create a idempotent package')
	group.add_option('-d','--desc',dest='desc',default=None,help='Set package description')
	parser.add_option_group(group)
	(options, args) = parser.parse_args()

	## Load configuration variables
	conf = scslib.sLoadConfig(options.config);

	## Build package path
	pkgcodir  = os.path.join(conf['dataroot'],'packages')

	## Deal with no args
	if len(args) <= 0:
		parser.print_help()
		return
		
	## Get metadata
	meta.load(conf['metadataPath'])
	## Call save on exit
	atexit.register(meta.save)
			
	## Shortcut to action
	action = args[0]

	#### PACKAGE CREATE ####################################################
	if action == 'create' and len(args) == 2:
		name = args[1]
		svnpath = os.path.join(conf['svnroot'],name)

		## the name must be unique across packages and channels
		if meta.data['channels'].has_key(name) or meta.data['packages'].has_key(name):
			inform.fatal("That name is already in use")

		## Create the SVN
		scslib.sCreateSVN(svnpath,name,conf)

		## Checkout the new SVN
		checkout = os.path.join(pkgcodir,name)
		svnclient.checkout('file://' + svnpath, checkout)

		try:
			os.mkdir(os.path.join(checkout,'scripts'))
			os.mkdir(os.path.join(checkout,'.scs'))
			os.mkdir(os.path.join(checkout,'data'))
			open(os.path.join(checkout,'scripts','preinit'),'w')
			open(os.path.join(checkout,'scripts','postinit'),'w')
			open(os.path.join(checkout,'scripts','uninit'),'w')
			open(os.path.join(checkout,'scripts','preup'),'w')
			open(os.path.join(checkout,'scripts','postup'),'w')
			open(os.path.join(checkout,'scripts','preinst'),'w')
			open(os.path.join(checkout,'scripts','postinst'),'w')
			open(os.path.join(checkout,'scripts','preinc'),'w')
			#open(os.path.join(checkout,'.scs','stepfree'),'w')
		except (OSError, IOError) as error:
			inform.fatal('Failed to create base components of package. Error was: ' + error.strerror + ' on ' + error.filename)
		else:
			svnclient.add(os.path.join(checkout,'scripts'),recurse=True)
			#svnclient.add(os.path.join(checkout,'.scs'),recurse=True)
			svnclient.add(os.path.join(checkout,'data'),recurse=True)
			revision = svnclient.checkin(checkout,"Package creation",recurse=True)

			## Record in meta.data for lating saving into metafile
			meta.data['packages'][name] = {'name': name}
			
			## Other options
			if options.stepfree:
				meta.data['packages'][name]['type'] = 'idempotent'
			else:
				meta.data['packages'][name]['type'] = 'transactional'
				
			if not options.desc == None:
				meta.data['packages'][name]['desc'] = options.desc

		## Cleanup in all cases
		shutil.rmtree(checkout)
		
	#### PACKAGE CREATE ####################################################
	elif action == 'clone' and len(args) == 3:
		oldname = args[1]
		newname = args[2]
		oldsvnpath = os.path.join(conf['svnroot'],oldname)
		newsvnpath = os.path.join(conf['svnroot'],newname)
		
		if not meta.data['packages'].has_key(oldname):
			inform.fatal("That package does not exist")		

		## the name must be unique across packages and channels
		if meta.data['channels'].has_key(newname) or meta.data['packages'].has_key(newname):
			inform.fatal("That name is already in use")

		## Clone the SVN
		scslib.sCloneSVN(oldsvnpath,newsvnpath,newname,conf)

		## Record in meta.data for lating saving into metafile
		meta.data['packages'][newname] = meta.data['packages'][oldname]
		meta.data['packages'][newname] = {'name': newname}
			
		## Other options
		if options.stepfree:
			meta.data['packages'][newname]['type'] = 'idempotent'
		else:
			meta.data['packages'][newname]['type'] = 'transactional'
				
		if not options.desc == None:
			meta.data['packages'][newname]['desc'] = options.desc
		else:
			meta.data['packages'][newname]['desc'] = 'Cloned from package ' + oldname
		
	#### PACKAGE SET #######################################################
	elif action == 'set' and len(args) == 4:
		pkgName  = args[1]
		prop     = args[2]
		value    = args[3]
		
		if not meta.data['packages'].has_key(pkgName):
			inform.fatal("That package does not exist")
		
		## DESC
		if prop == 'desc':
				meta.data['packages'][pkgName][prop] = value
		else:
			inform.fatal("No such property")

	#### PACKAGE DELETE ####################################################
	elif action == 'delete' and len(args) == 2:
		name = args[1]

		## Make sure it exists
		if not meta.data['packages'].has_key(name):
			inform.fatal("Sorry, that package does not exist")
		else:
			scslib.sDeleteSVN(os.path.join(conf['svnroot'],name))
			del(meta.data['packages'][name])

	#### PACKAGE LIST ######################################################
	elif action == 'list':
		pkgNames = sorted(meta.data['packages'].keys())
		
		for pkgname in pkgNames:
			pkgdict = meta.data['packages'][pkgname]
			
			if pkgdict.has_key('desc'):
				print pkgdict['name'] + ' (' + pkgdict['desc'] + ')'
			else:
				print pkgdict['name'] + ' (No description set)'	
			
	else:
		parser.print_help()

	## Save metadata
	meta.save()

if __name__ == "__main__":
	if sys.version < '2.6':
		sys.stderr.write('Python 2.6 or greater is required for this program. Exiting.')
	else:
	    main()
